# Change these first
owner: surreal-ai # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees:
  - shonenada
  - buffxz
sites:
  - name: homepage
    url: https://www.surreal.la/home
  - name: ai-renaissance
    url: https://www.surreal.la/ai-renaissance
  - name: Product
    url: https://product.surreal-ai.com
  - name: Vinci
    url: https://vinci.surreal-ai.com
  - name: ef-api
    url: https://craft-api.surreal-ai.com/v1/health_check
  - name: extend-api
    url: https://extend-api.surreal-ai.com/v1/extend/health_check
  - name: talking-avatar
    url: https://craft-api.surreal-ai.com/v1/talking_avatar/health_check
  - name: movio
    url: https://craft-api.surreal-ai.com/pacific/v1/pacific/health_check


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: upptime.intra.surreal-ai.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  baseUrl: /upptime # where "repo" is your repository name
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
